-- =====================================================================
-- DATA_2026-09-05_social-groups-remaining-insert.sql
-- Muc dich: hoan tat migrate du lieu Social Groups tu Google Sheet
--   "social group url" (tab "FB Group") vao social_group_urls, phan
--   con thieu sau khi Claude da chay dang chung 800/1028 (sandbox) va
--   1000/1028 (public) truoc khi dung lai theo dung vai tro Architect/QA.
-- Da lam truoc do (KHONG can lam lai):
--   - ALTER TABLE them cot member_count (int) tren ca 2 schema.
--   - Da dang ky 12 tag moi vao social_group_tags (ca 2 schema): Mechanical,
--     Mechatronics, Industrial Automation, Industrial, IT, Dev, QA, BA, PM,
--     Network IT, Infrastructure IT, Devops (2 tag "Network (IT)" va
--     "Infrastructure (IT)" trong sheet goc DA duoc doi ten bo dau ngoac
--     vi charset constraint social_group_tags_name_charset_check khong
--     cho phep ky tu ( ) -- ĐÃ duoc User xac nhan dong y cach xu ly nay).
--   - Da XOA toan bo campaigns + social_group_urls cu (Cosmetic/Marketing/
--     Nontech/Nurse/Video Editor/Facebook Group va cac campaign gan voi
--     chung) tren ca 2 schema theo yeu cau User (thay database cu bang
--     database moi tu Google Sheet).
--   - Da insert 1000/1028 dong vao public.social_group_urls (con thieu
--     28 dong cuoi cung, sheet row 1001-1028).
--   - Da insert 800/1028 dong vao sandbox.social_group_urls (con thieu
--     228 dong cuoi cung, sheet row 801-1028).
-- Viec AG can lam: CHAY DUNG NGUYEN VAN file SQL nay 1 lan (qua Supabase
--   MCP hoac psql) de bo sung dung phan con thieu. KHONG chay lai toan
--   bo 1028 dong (se tao du lieu trung vi social_group_urls khong co
--   unique constraint tren cot url).
-- Sau khi chay xong, verify: public + sandbox deu phai co dung 1028
--   dong trong social_group_urls (xem query verify o cuoi file).
-- =====================================================================

-- PHAN 1: bo sung 28 dong con thieu cho PUBLIC (sheet row 1001-1028)
INSERT INTO public.social_group_urls (name, url, group_type, member_count, is_active) VALUES
('Kỹ Sư Nhật Bản - Việc Làm', 'https://www.facebook.com/groups/2023790564767783/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 54000, true),
('Kỹ sư cầu nối (BrSE) HCM -HN -Nhật Bản', 'https://www.facebook.com/groups/309707408780063/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 942, true),
('Cộng đồng kỹ sư CAD-CAM-CAE tại Nhật', 'https://www.facebook.com/groups/kysunhatchuyenviecmienphi/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 32000, true),
('Tuyển dụng - Kỹ Sư- Kỹ thuật- Giám đốc điều hành', 'https://www.facebook.com/groups/2496241820607060/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 5800, true),
('Nhóm Kỹ sư cầu nối - Brse Việt Nhật', 'https://www.facebook.com/groups/905408546544190/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3700, true),
('Cộng Đồng Kỹ Sư MEPF Việt Nam', 'https://www.facebook.com/groups/1251246873045686/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3000, true),
('THÔNG TIN VIỆC LÀM CHO KỸ SƯ-CỬ NHÂN-SINH VIÊN - CƠ KHÍ', 'https://www.facebook.com/groups/vlck25/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6300, true),
('Hội Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/1987624372089344/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 386, true),
('Kỹ Sư Cầu Nối - BrSE Tiếng Nhật', 'https://www.facebook.com/groups/2577015569127429/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1000, true),
('KỸ SƯ XÂY DỰNG NHẬT BẢN', 'https://www.facebook.com/groups/kysuxaydungonhat/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 47000, true),
('Cộng đồng kỹ sư bán hàng (Sale Engineer)', 'https://www.facebook.com/groups/302965937335953/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9000, true),
('設計職専用サイト_CỘNG ĐỒNG KỸ SƯ THIẾT KẾ VIỆT-NHẬT', 'https://www.facebook.com/groups/329197685357077/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3700, true),
('🏡 TUYỂN DỤNG VIỆC LÀM KIẾN TRÚC SƯ - KỸ SƯ XÂY DỰNG - THIẾT KẾ NỘI THẤT', 'https://www.facebook.com/groups/tuyendungvieclamkientrucnoithat02/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 110000, true),
('Kỹ sư xây dựng Việt Nam', 'https://www.facebook.com/groups/201018707897745/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 7300, true),
('Tuyển Dụng Kỹ Sư Xây Dựng - Kiến Trúc Sư - Nội Thất', 'https://www.facebook.com/groups/2188380784744724/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3500, true),
('Trường ĐH Công nghệ kỹ thuật TPHCM (Sư phạm kỹ thuật TPHCM)', 'https://www.facebook.com/groups/huynhvanson/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 43000, true),
('HỘI KỸ SƯ Ô TÔ VIỆT NAM', 'https://www.facebook.com/groups/httpswww.facebook.comdemigodkylin1905/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 87000, true),
('Việc Làm Cơ Điện/ME/HVAC/PCCC - Vieclamkythuat.com', 'https://www.facebook.com/groups/1911637015973925/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 11000, true),
('Kỹ sư chuyển việc tại Nhật Bản (日本で転職する仕事) ✅', 'https://www.facebook.com/groups/756457659679335/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 167000, true),
('Kỹ sư IT, BA, Tester, PM tiếng Hàn', 'https://www.facebook.com/groups/ithanquoc/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4900, true),
('Kỹ Sư Cầu Nối', 'https://www.facebook.com/groups/1971961879726011/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2600, true),
('Cộng Đồng Kỹ Sư Nhật Bản', 'https://www.facebook.com/groups/359031044523161/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 53000, true),
('Kỹ Sư Cơ Khí & Việc Làm', 'https://www.facebook.com/groups/482136141817760/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 49000, true),
('KỸ SƯ NHẬT BẢN ( Cộng Đồng Kỹ Sư Đi Mới - Chuyển Việc )', 'https://www.facebook.com/groups/994259058348355/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 119000, true),
('VIỆC LÀM CƠ KHÍ CNC - KỸ SƯ SẢN XUẤT', 'https://www.facebook.com/groups/2227760201360008/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 42000, true),
('Kỹ Sư Cơ khí Tìm Việc Làm', 'https://www.facebook.com/groups/131072731022774/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6200, true),
('Việc cho người làm cơ khí ( Thợ hàn, kỹ sư, quản đốc, kỹ thuật..)', 'https://www.facebook.com/groups/viecchonguoilamcokhi/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6800, true),
('Kỹ Sư Cơ Điện M&E', 'https://www.facebook.com/groups/421177733980982/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3200, true);
-- PHAN 2: bo sung 228 dong con thieu cho SANDBOX (sheet row 801-1028)
INSERT INTO sandbox.social_group_urls (name, url, group_type, member_count, is_active) VALUES
('VIỆC LÀM KỸ SƯ XÂY DỰNG', 'https://www.facebook.com/groups/1216354709103792/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 11000, true),
('Tuyển dụng kỹ sư trắc đạc công trình', 'https://www.facebook.com/groups/705763703926497/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 13000, true),
('Tuyển Dụng Kỹ Sư Xây Dựng Toàn Quốc', 'https://www.facebook.com/groups/tuyendungkysuxaydungtoanquoc/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 41000, true),
('kỹ sư xây dựng công trình', 'https://www.facebook.com/groups/1564759780452532/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 65000, true),
('Tuyển Dụng Kỹ Sư Xây Dựng✅', 'https://www.facebook.com/groups/533992475516984/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 17000, true),
('Hội kỹ sư Tư vấn giám sát công trình Xây dựng, Thủy lợi, Giao thông', 'https://www.facebook.com/groups/207780936288299/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 29000, true),
('Việc Làm Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/819709073810163/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 5000, true),
('Tuyển Dụng Kỹ Sư Chuyên Ngành HVAC - M&E', 'https://www.facebook.com/groups/333293425284475/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 24000, true),
('TUYỂN DỤNG VIỆC LÀM KỸ SƯ XÂY DỰNG', 'https://www.facebook.com/groups/180838332514702/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 12000, true),
('Tuyển dụng ngành xây dựng (Kỹ sư, Giám sát, Dự toán, QS,...)', 'https://www.facebook.com/groups/643322861727948/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4100, true),
('Việc Làm Xây Dựng - Kỹ Sư Kinh Tế Xây dựng, kỹ sư Qs, khối lượng dự toán...', 'https://www.facebook.com/groups/222258178959853/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 42000, true),
('Tuyển dụng ngành xây dựng (Kỹ sư, Giám sát, Qs,…)', 'https://www.facebook.com/groups/906359225373316/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9800, true),
('Kỹ sư QA/QC Xây Dựng', 'https://www.facebook.com/groups/910939024220101/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4200, true),
('Tuyển Dụng Kỹ Sư Xây Dựng Miền Bắc', 'https://www.facebook.com/groups/529264295861512/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4200, true),
('Việc Làm Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/967366953968991/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 14000, true),
('Tuyển dụng kỹ sư xây dựng không yêu cầu kinh nghiệm', 'https://www.facebook.com/groups/kysuxaydungtoanquoc/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 8000, true),
('Hội kỹ sư công trình', 'https://www.facebook.com/groups/kscongtrinh/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 13000, true),
('Tuyển Dụng Kỹ Sư Kinh Tế Xây Dựng ( QS Engineer )', 'https://www.facebook.com/groups/807412874119647/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 12000, true),
('TUYỂN DỤNG KIẾN TRÚC SƯ - KỸ SƯ XÂY DỰNG', 'https://www.facebook.com/groups/Sketchup/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9800, true),
('Tuyển dụng Kỹ sư QS - Kinh Tế Xây dựng', 'https://www.facebook.com/groups/knxaydung/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 10000, true),
('Cộng đồng Kỹ sư Điện Công Nghiệp', 'https://www.facebook.com/groups/congdongkysudiencongnghiep/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 35000, true),
('Tuyển Dụng Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/419312256864139/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 13000, true),
('Tuyển Dụng Kỹ Sư QS - Kinh Tế Xây Dưng', 'https://www.facebook.com/groups/845310484160666/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 15000, true),
('Kỹ Sư M&E - Kỹ Sư Cơ Điện Công Trình', 'https://www.facebook.com/groups/564052757116043/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 65000, true),
('Chuyển việc kỹ sư', 'https://www.facebook.com/groups/kysunhatbantimdonmienphi/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 57000, true),
('TUYỂN DỤNG KỸ SƯ XÂY DỰNG', 'https://www.facebook.com/groups/1005792434199854/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9500, true),
('Nhóm Kỹ Sư Xây Dựng Việt Nam', 'https://www.facebook.com/groups/nhomkysuxaydungvietnam/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 48000, true),
('Hội Kỹ Sư Việt Nam', 'https://www.facebook.com/groups/hoikysuvietnam/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 10000, true),
('TUYỂN DỤNG KỸ SƯ XÂY DỰNG ✅', 'https://www.facebook.com/groups/tuyendungkysuxd/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 8500, true),
('Tuyển kỹ sư xây dựng dân dụng', 'https://www.facebook.com/groups/557177631379838/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 13000, true),
('Nhóm Kỹ Sư Xây Dựng Việt Nam', 'https://www.facebook.com/groups/kysuxaydungvn/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 41000, true),
('Hội kỹ sư xây dựng - Tuyển dụng kỹ sư xây dựng', 'https://www.facebook.com/groups/kinhnghiemthicongcongtrinh/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 19000, true),
('Kỹ sư XÂY DỰNG 3 MIỀN, BẮC - TRUNG - NAM', 'https://www.facebook.com/groups/989111202701875/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 10000, true),
('Tuyển dụng kỹ sư QS - Kỹ sư Kinh tế Xây dựng', 'https://www.facebook.com/groups/httpstuyendungxaydung.vn/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 74000, true),
('Tuyển Dụng Kỹ Sư Xây Dựng - Giao Thông - Kiến Trúc - Thủy Lợi', 'https://www.facebook.com/groups/560146747713467/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 56000, true),
('HỘI KỸ SƯ XÂY DỰNG VIỆT NAM ✅', 'https://www.facebook.com/groups/251657075212986/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 83000, true),
('Tuyển Dụng Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/tdksxd/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 10000, true),
('Tuyển Dụng Kỹ Sư QA,QC,QS - M&E', 'https://www.facebook.com/groups/348518190549788/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 21000, true),
('Tuyển Cung Ứng Kỹ Thuật ( Foxconn Luxshare Geortek Biel Quanta BYD )', 'https://www.facebook.com/groups/1385942826100826/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4000, true),
('Tôi Là Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/1344871899724811/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 21000, true),
('Hội Kiến Trúc Sư Và Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/483861155107667/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 16000, true),
('Kênh tuyển dụng kiến trúc sư, kỹ sư xây dựng', 'https://www.facebook.com/groups/cadjobchannel/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 18000, true),
('Tuyển dụng Kỹ sư Xây dựng Công trường (Mọi vị trí)', 'https://www.facebook.com/groups/2413493598969935/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6900, true),
('Hội Kỹ Sư Xây Dựng Việt Nam', 'https://www.facebook.com/groups/700896151054213/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9300, true),
('Tuyển dụng Kỹ sư Qs - Kinh tế xây dựng', 'https://www.facebook.com/groups/tdksqsktxd/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 57000, true),
('Tuyển Dụng Kỹ Sư - Tìm Việc Làm Kỹ Thuật', 'https://www.facebook.com/groups/471942337357732/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 81000, true),
('Kỹ Sư Chuyển Việc', 'https://www.facebook.com/groups/vieclamnhatbanmienphi/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 83000, true),
('Kỹ Sư Xây Dựng & Chuyện Đi Làm', 'https://www.facebook.com/groups/1905557583498114/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 181, true),
('Việc Làm Kỹ Thuật Tiếng Trung | Luxshare - Fukang - Goertek - Foxconn', 'https://www.facebook.com/groups/1317322607228909/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 141, true),
('Tin tuyển dụng kỹ sư cơ điện', 'https://www.facebook.com/groups/2274386122731547/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1300, true),
('Kỹ Sư Chuyển Việc', 'https://www.facebook.com/groups/kysuthietkenhatban/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 10000, true),
('VIỆC LÀM KỸ THUẬT, KỸ SƯ TẠI BẮC NINH - BẮC GIANG', 'https://www.facebook.com/groups/vieclamkythuat.bn/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 41000, true),
('Cộng Đồng Cung Ứng Kỹ Thuật & Kỹ Sư - Miền Bắc', 'https://www.facebook.com/groups/2353395688476869/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3100, true),
('KỸ SƯ CƠ - ĐIỆN (MEPF) TÌM VIỆC', 'https://www.facebook.com/groups/396914852295110/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1000, true),
('Hội Kỹ Sư Điện', 'https://www.facebook.com/groups/hoikysudien67/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 25000, true),
('Tuyển dụng kỹ sư cấp thoát nước, kỹ sư môi trường', 'https://www.facebook.com/groups/579315179155975/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9400, true),
('TUYỂN DỤNG, TÌM VIỆC, KỸ SƯ XÂY DỰNG, KS CƠ KHÍ, TEKLA, BIM, QS, QC', 'https://www.facebook.com/groups/244114121593322/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2200, true),
('Tuyển dụng Kỹ sư xây dựng Qs/Qa/Qc', 'https://www.facebook.com/groups/839066761200969/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 10000, true),
('Tuyển dụng kỹ sư Xây Dựng tại Hà Nội✅', 'https://www.facebook.com/groups/1146480252968781/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 5200, true),
('Cộng đồng Kỹ Sư Bách Khoa', 'https://www.facebook.com/groups/441344186601319/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1500, true),
('Tuyển Dụng Kỹ Sư Xây Dựng Miền Nam', 'https://www.facebook.com/groups/tuyendungkysuxaydungmiennam/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 86000, true),
('VIECLAMFB.VN - VIỆC LÀM KỸ SƯ XÂY DỰNG / KỸ SƯ CẦU ĐƯỜNG / KỸ SƯ CÔNG TRÌNH', 'https://www.facebook.com/groups/2161949004618607/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 509, true),
('Tuyển Dụng Kỹ Sư PCCC và Cơ Điện M&E', 'https://www.facebook.com/groups/1845889309459911/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1500, true),
('Cộng đồng kỹ sư mạng Việt Nam - Vietnam Network Engineer', 'https://www.facebook.com/groups/vietnamnetworkengineer/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 16000, true),
('HỘI KỸ SƯ XD VÀ THIẾT KẾ KẾT CẤU CÔNG TRÌNH', 'https://www.facebook.com/groups/367948286645562/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4900, true),
('Tuyển dụng kỹ sư M&E, ngành điện,….', 'https://www.facebook.com/groups/1568720294004414/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 5500, true),
('Tuyển Dụng Kỹ Sư Xây Dựng Miền Nam', 'https://www.facebook.com/groups/1899892447020209/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3800, true),
('Việc làm kỹ thuật dành cho công nhân, thợ, kỹ thuật viên', 'https://www.facebook.com/groups/2104579246436934/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9800, true),
('HỘI KỸ SƯ THIẾT KẾ ĐIỆN', 'https://www.facebook.com/groups/2180132768923411/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3200, true),
('TUYỂN DỤNG KỸ SƯ ☑️', 'https://www.facebook.com/groups/253299084776535/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 114000, true),
('Hội Kỹ Sư Cơ Điện (MEPF)', 'https://www.facebook.com/groups/hoikysucodienmepf/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 12000, true),
('Tư Vấn giám sát -kỹ sư xây dựng', 'https://www.facebook.com/groups/499257656472143/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4000, true),
('TUYỂN DỤNG KỸ SƯ XÂY DỰNG, KIẾN TRÚC SƯ, MEP', 'https://www.facebook.com/groups/4150355021847400/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 620, true),
('KỸ SƯ XÂY DỰNG', 'https://www.facebook.com/groups/2805719833088380/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 12000, true),
('Việc Làm Kỹ Sư Xây Dựng 2025- Vieclamkythuat.com', 'https://www.facebook.com/groups/1101783507648900/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 12000, true),
('Việc làm kỹ sư cơ điện - Mechanical, Electrical, HVAC, Chiller Engineer', 'https://www.facebook.com/groups/vieclamhvac/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 22000, true),
('✅Tuyển dụng Kiến Trúc Sư - Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/tuyendungkientrucsu.kysuxaydung/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1200, true),
('Tuyển dụng ngành xây dựng (Kỹ sư, Giám sát, QS,......)', 'https://www.facebook.com/groups/1094750698190931/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 72000, true),
('Tuyển Dụng Ngành Xây Dựng (Kỹ sư, Giám sát, Dự Toán, QS/QC,...)', 'https://www.facebook.com/groups/1550721822905430/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 8200, true),
('Tuyển dụng Kỹ sư Dự Án - Phát triển dự án', 'https://www.facebook.com/groups/279595260439131/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 8300, true),
('Tuyển Dụng Kỹ Sư Xây Dựng Hà Nội✅️', 'https://www.facebook.com/groups/1813445352330487/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2100, true),
('KỸ SƯ XÂY DỰNG VIỆT NAM', 'https://www.facebook.com/groups/3403184489992286/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 5700, true),
('Tuyển dụng kỹ sư xây dựng - Việt Nam', 'https://www.facebook.com/groups/512308539731733/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4500, true),
('TUYỂN DỤNG KỸ SƯ QS-DỰ TOÁN-KINH TẾ XÂY DỰNG TẠI HCM', 'https://www.facebook.com/groups/237036146501080/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 41000, true),
('Tuyển Dụng Kỹ Sư Chuyên Ngành PCCC - M&E', 'https://www.facebook.com/groups/430281065528789/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 13000, true),
('Hội Kỹ Sư Xây Dựng Hồ Chí Minh', 'https://www.facebook.com/groups/kysuxaydung.tphcm/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4700, true),
('KỸ SƯ XE', 'https://www.facebook.com/groups/congthongtinvieclamnganhoto/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 53000, true),
('TUYỂN DỤNG KỸ SƯ QLDA, TVGS, CHỈ HUY TRƯỞNG, CÁN BỘ KỸ THUẬT CHẤT LƯỢNG CAO', 'https://www.facebook.com/groups/4083144378596050/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2900, true),
('VIỆC LÀM XÂY DỰNG- KỸ THUẬT PHÍA NAM', 'https://www.facebook.com/groups/171046548203763/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 30000, true),
('Hội kỹ sư Kinh tế xây dựng-Quản lý dự án', 'https://www.facebook.com/groups/hoikysukinhtexaydungvn/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3400, true),
('Kỹ sư chuyển việc tại Nhật Bản (日本で転職する仕事)', 'https://www.facebook.com/groups/vieclamtimnguoi/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 81000, true),
('Tuyển Dụng Kỹ Sư Xây Dựng Lương Cao', 'https://www.facebook.com/groups/1469951967537861/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1100, true),
('Việc làm Kỹ sư Xây dựng | M&E - QS - QA/QC - Giám sát | Toàn quốc ✅', 'https://www.facebook.com/groups/2325263171629004/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 43, true),
('Chuyển việc kỹ sư', 'https://www.facebook.com/groups/congdongthietkexaydungnhatban/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 31000, true),
('TUYỂN DỤNG KIẾN TRÚC SƯ, KỸ SƯ CẤP THOÁT NƯỚC, KỸ SƯ ĐIỆN', 'https://www.facebook.com/groups/876523296017134/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9600, true),
('Chuyển việc kỹ sư', 'https://www.facebook.com/groups/2569186776576714/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 77000, true),
('Việc làm Kỹ sư tại Hải Phòng', 'https://www.facebook.com/groups/kysuhaiphong/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 5300, true),
('Cộng Đồng Kỹ Sư Việt Nam', 'https://www.facebook.com/groups/4062886120615915/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 706, true),
('Tuyển dụng kỹ sư xây dựng ✅', 'https://www.facebook.com/groups/437483282084594/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 39000, true),
('CHUYỂN VIỆC KỸ SƯ', 'https://www.facebook.com/groups/chuyenvieckysutokuteiginou/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 39000, true),
('Tuyển Dụng Kỹ Sư Xây Dựng✅', 'https://www.facebook.com/groups/750241183748930/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 61000, true),
('Tuyển Dụng Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/473770708101612/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 19000, true),
('Tuyển Dụng Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/tuyendungkysuxaydung365/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 88000, true),
('KỸ SƯ NHẬT BẢN ( Cộng Đồng Kỹ Sư Đi Mới - Chuyển Việc )', 'https://www.facebook.com/groups/kysunhatban.jp/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 27000, true),
('VIỆC LÀM KỸ SƯ XÂY DỰNG', 'https://www.facebook.com/groups/vieclamkysuxaydung/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 53000, true),
('Tuyển dụng kỹ sư xây dựng Thanh Hóa', 'https://www.facebook.com/groups/1609361332659661/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 14000, true),
('Tuyển dụng kỹ sư mới ra trường', 'https://www.facebook.com/groups/2816635678560120/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 27000, true),
('Kỹ Sư Nhật Bản Tìm Đơn ✅', 'https://www.facebook.com/groups/1126795095337899/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 234000, true),
('KỸ SƯ XÂY DỰNG', 'https://www.facebook.com/groups/ksxaydung/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 140000, true),
('Hội Kỹ Sư Cơ Điện SPKT', 'https://www.facebook.com/groups/1143551039002568/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 41000, true),
('Cung Ứng Kỹ Thuật Miền Bắc – Kết Nối Kỹ Thuật', 'https://www.facebook.com/groups/1333491068481195/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 12000, true),
('Cộng đồng kỹ sư IT SE BrSE tại Nhật', 'https://www.facebook.com/groups/congdongkysuit/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 907, true),
('Việc Làm Kỹ Sư Môi Trường - Cấp Thoát Nước', 'https://www.facebook.com/groups/1536192944211840/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2500, true),
('KỸ SƯ ĐÀI LOAN-Trao đổi ✅', 'https://www.facebook.com/groups/kysudailoan/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4000, true),
('Kỹ Sư Chuyển Việc', 'https://www.facebook.com/groups/kysunhatbanchuyenviec.jp/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 21000, true),
('VIỆC LÀM KỸ SƯ BÁCH KHOA - CÔNG NGHỆ - PTIT - HV KTQS - CÔNG NGHIỆP HN', 'https://www.facebook.com/groups/1336830303654893/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 5000, true),
('Việc Làm Kỹ Sư Thiết Kế CAD, CAM, SOLIDWORK, CATIA', 'https://www.facebook.com/groups/2064136433665008/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6700, true),
('HỘI KỸ SƯ CẦU ĐƯỜNG', 'https://www.facebook.com/groups/caulacbosolidworks/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 30000, true),
('Kỹ sư cầu nối (BSE) Việt - Nhật', 'https://www.facebook.com/groups/508988885878504/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 8200, true),
('Kỹ Sư Xây Dựng - Việc Làm & Chuyện Nghề', 'https://www.facebook.com/groups/327245868623702/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 579, true),
('Kỹ sư mỏ', 'https://www.facebook.com/groups/181473485802633/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 5400, true),
('KỸ SƯ CẤP THOÁT NƯỚC VÀ MÔI TRƯỜNG', 'https://www.facebook.com/groups/kysucapthoatnuocvamoitruong/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 34000, true),
('NHÓM VIỆC LÀM KỸ SƯ CƠ ĐIỆN. MEPF', 'https://www.facebook.com/groups/465182671174087/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4600, true),
('Chuyển Việc Kỹ Sư', 'https://www.facebook.com/groups/966685336723674/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 11000, true),
('Chuyển việc kỹ Sư', 'https://www.facebook.com/groups/kysutimviecnhatban/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 34000, true),
('Tuyển Dụng Kỹ Sư Chuyên Ngành Điện, Điện Nhẹ - M&E', 'https://www.facebook.com/groups/5310620225636613/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 17000, true),
('Tuyển Dụng Kỹ Sư SHOP & DESIGN - M&E', 'https://www.facebook.com/groups/926986591332888/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3100, true),
('TUYỂN DỤNG KỸ SƯ QS/QC (KHÔNG NỢ LƯƠNG)', 'https://www.facebook.com/groups/330439929531706/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2000, true),
('Kỹ sư-QS-QA-QC-chuyên viên-leader xây dựng', 'https://www.facebook.com/groups/3069460359887846/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 804, true),
('Tuyển dụng ngành Môi trường (Kỹ sư, Giám sát, QS, Dự toán ...)', 'https://www.facebook.com/groups/690162810522211/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4100, true),
('Chuyển việc kỹ sư', 'https://www.facebook.com/groups/aoc39/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 69000, true),
('VIỆC LÀM NHÂN VIÊN KỸ THUẬT KỸ SƯ KCN BẮC NINH', 'https://www.facebook.com/groups/2385810321523082/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 34000, true),
('Việc làm kỹ thuật, bảo trì, sửa chữa, sản xuất ..', 'https://www.facebook.com/groups/vieclamkythuatsanxuat/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 25000, true),
('Tuyển dụng Kỹ sư Kinh tế Xây dựng - Kỹ sư QS/QC Cơ Điện MEP', 'https://www.facebook.com/groups/1461313641747586/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 872, true),
('VIỆC LÀM DỰ TOÁN, QA, QS, KINH TẾ XÂY DỰNG', 'https://www.facebook.com/groups/nhathauxaydungsaigon/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 32000, true),
('TUYỂN DỤNG KỸ SƯ XÂY DỰNG MIỀN NAM ✅️', 'https://www.facebook.com/groups/1610092002740685/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 705, true),
('KỸ SƯ NHẬT BẢN', 'https://www.facebook.com/groups/211774544821059/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 17000, true),
('Việc làm kỹ thuật miền bắc', 'https://www.facebook.com/groups/vieclamkythuatmienbac/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6900, true),
('Kỹ Sư Nhật Bản Tìm Đơn (技術・人文知識・国際業務)', 'https://www.facebook.com/groups/601609421436138/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 94000, true),
('TUYỂN DỤNG KỸ SƯ XÂY DỰNG VIỆT NAM', 'https://www.facebook.com/groups/1627864407452682/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 20000, true),
('Tuyển dụng kỹ sư xây dựng', 'https://www.facebook.com/groups/tuyendungkysuchatluongcao/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1600, true),
('VIỆC LÀM KỸ THUẬT TOÀN QUỐC ⚙✅', 'https://www.facebook.com/groups/1456759544865029/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 7300, true),
('Việc Làm Kỹ Thuật Điện, Điện Tử, CNTT TPHCM', 'https://www.facebook.com/groups/2157342101245635/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9600, true),
('Tuyển Dụng Kỹ Sư Xây Dựng -HCM ✅', 'https://www.facebook.com/groups/1152447085385782/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1300, true),
('CỘNG ĐỒNG KỸ SƯ Ô TÔ VIỆT NAM - AUTOMOTIVE ENGINEERING', 'https://www.facebook.com/groups/168020742157358/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 10000, true),
('Vùng kín Kỹ Sư', 'https://www.facebook.com/groups/tamsudoikysu/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 103000, true),
('Kiến thức cho Kỹ sư trẻ', 'https://www.facebook.com/groups/5498287703574967/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9900, true),
('Tuyển Dụng Kỹ Sư Xây Dựng TP.HCM ✅', 'https://www.facebook.com/groups/3247264718825395/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 8200, true),
('Kỹ Sư Xây Dựng Nhật Bản', 'https://www.facebook.com/groups/kysutimvieconhatban/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 39000, true),
('Hội Kỹ Sư Điện-Tự Động Hóa-Lập trình PLC Mitsubishi Tại Nhật', 'https://www.facebook.com/groups/tdhviepan/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 26000, true),
('Tuyển dụng Sales Kỹ Thuật - CNTT- Sales Engineer - Sales IT- Kỹ sư bán hàng', 'https://www.facebook.com/groups/saleskythuat/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 13000, true),
('Tuyển dụng kỹ sư điện mặt trời', 'https://www.facebook.com/groups/kysudienmattroi/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 13000, true),
('Chuyển Việc Kỹ Sư', 'https://www.facebook.com/groups/chuyenvieckysu1/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 15000, true),
('VIỆC LÀM KỸ THUẬT TOÀN QUỐC', 'https://www.facebook.com/groups/792355860500726/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1600, true),
('Kỹ sư xây dựng', 'https://www.facebook.com/groups/1587223114827275/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3300, true),
('Hội các kỹ sư xây dựng TPHCM', 'https://www.facebook.com/groups/426384327564105/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9800, true),
('Tuyển dụng ngành xây dựng (Kỹ sư, Giám sát, QS,......)', 'https://www.facebook.com/groups/623604169620665/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 97000, true),
('TUYỂN DỤNG KỸ SƯ XÂY DỰNG MIỀN NAM', 'https://www.facebook.com/groups/475989244671919/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 27000, true),
('Tuyển Dụng Kỹ Sư Xây Dựng Toàn Quốc', 'https://www.facebook.com/groups/918654627427399/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1400, true),
('Tuyển dụng kiến truc sư -kỹ sư -nhân sự Ngành Nội Thất, Xây Dựng', 'https://www.facebook.com/groups/142837976345843/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 51000, true),
('Kênh Tuyển Dụng Kiến Trúc Sư, Kỹ Sư Xây Dựng, Họa Viên', 'https://www.facebook.com/groups/kwanxwan/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6900, true),
('Việc làm Kỹ sư cơ khí & xây dựng giao thông thủy lợi việt nam', 'https://www.facebook.com/groups/227174707122887/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 31000, true),
('Hội Kỹ Sư Điện-Tự Động Hóa-Lập trình PLC Mitsubishi Tại Nhật', 'https://www.facebook.com/groups/kysuthietkenhatban.jp/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 19000, true),
('Hội Kỹ Sư Và Kiến Trúc Sư Xây Dựng', 'https://www.facebook.com/groups/hoikysuvakientrucsuxaydung/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 215000, true),
('Chuyển việc kỹ sư', 'https://www.facebook.com/groups/hoikysuchuyenviecnhatban/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 11000, true),
('Tuyendungkysucodien.com - Tuyển Dụng Kỹ Sư Cơ Điện', 'https://www.facebook.com/groups/679256808254789/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3800, true),
('Kỹ Sư Nhật Bản ✅ - Xí Nghiệp Tuyển Trực Tiếp', 'https://www.facebook.com/groups/1440056363387084/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 233000, true),
('TUYỂN DỤNG KỸ SƯ HÀ NỘI ✅️', 'https://www.facebook.com/groups/795030265091153/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6700, true),
('Hội Kỹ Sư Xây Dựng ✅', 'https://www.facebook.com/groups/tuyendungkysuxaydung/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 159000, true),
('Tuyển Dụng Ngành Xây Dựng (Kỹ Sư, Giám Sát, Dự Toán, QS,.......)', 'https://www.facebook.com/groups/1409241390961861/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 175, true),
('TUYỂN DỤNG KỸ SƯ XÂY DỰNG NGHỆ TĨNH', 'https://www.facebook.com/groups/594978761660784/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 7800, true),
('Tuyển dụng Kỹ sư Cơ điện MEP (Giám sát, Chỉ huy trưởng, QS, QC, HSE)', 'https://www.facebook.com/groups/774115061833837/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1700, true),
('Hội những kỹ sư, giám sát điện công trình tại Việt Nam - Vietnam M&E', 'https://www.facebook.com/groups/333453203660232/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2900, true),
('Tuyển Dụng _ Kỹ Sư QA/QC - Quản Lý Chất Lượng', 'https://www.facebook.com/groups/4399395253466191/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 17000, true),
('Hội Kỹ Sư Điện Tại Nhật Bản ・電気工事士・電気施工管理技士', 'https://www.facebook.com/groups/hoikysudiennhatban/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 26000, true),
('KỸ SƯ CƠ ĐIỆN SPKT', 'https://www.facebook.com/groups/me.engineer.spkt/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4100, true),
('Diễn Đàn Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/263647174265555/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4200, true),
('Việc làm KỸ SƯ BÁN DẪN VIỆT NAM, SINGAPORE, US - SEMICONDUCTOR ENGINEER job', 'https://www.facebook.com/groups/564610063560657/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3300, true),
('Cộng Đồng Hướng Nghiệp Kỹ Sư Việt Nam', 'https://www.facebook.com/groups/kysu365/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3600, true),
('Tuyển Dụng Kỹ Sư Kết Cấu', 'https://www.facebook.com/groups/629810985720729/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 13000, true),
('TUYỂN DỤNG KỸ SƯ XÂY DỰNG TOÀN QUỐC✅', 'https://www.facebook.com/groups/939648017218593/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2100, true),
('Hội Kỹ Sư Kinh Tế Xây Dựng', 'https://www.facebook.com/groups/441786346021588/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 13000, true),
('Tuyển dụng Kỹ sư xây dựng', 'https://www.facebook.com/groups/1031451561134853/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2500, true),
('Thiết kế Cơ khí_UTT', 'https://www.facebook.com/groups/382204622482555/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2800, true),
('Kỹ Sư Nhật Bản Tìm Đơn (技術・人文知識・国際業務) ✅', 'https://www.facebook.com/groups/1114469272364127/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 73000, true),
('Kỹ sư Nhật Bản việc làm', 'https://www.facebook.com/groups/vieclamkysu/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 110000, true),
('VIỆC LÀM KỸ THUẬT - KINH DOANH KỸ THUẬT', 'https://www.facebook.com/groups/1296474500447686/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 20000, true),
('Tuyển dụng - Việc làm kỹ sư xây dựng', 'https://www.facebook.com/groups/1516571335070367/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 48000, true),
('Kỹ Sư Xây Dựng Dân Dụng & Cầu Đường', 'https://www.facebook.com/groups/660224330814820/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 52000, true),
('Hội Kỹ Sư Khối Kỹ Thuật Nhật Bản', 'https://www.facebook.com/groups/rikijinzaivieclamtiengnhat/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1800, true),
('🏡 Tuyển Dụng Kiến Trúc Sư-Thiết Kế Nội Thất-Kỹ Sư-Kết Cấu-Bim Modeler-Mep✅', 'https://www.facebook.com/groups/631540095225978/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 86000, true),
('Tuyển Dụng Kỹ Sư QA,QC,QS - Xây Dựng', 'https://www.facebook.com/groups/941188514954479/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 603, true),
('HỘI TUYỂN DỤNG KỸ SƯ CƠ ĐIỆN ME', 'https://www.facebook.com/groups/561302733299191/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4100, true),
('Cộng Đồng Kỹ Sư, Nhân Viên Kỹ Thuật, Sale Kỹ Thuật Việt Nam', 'https://www.facebook.com/groups/congdongkythuatvietnam/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 54, true),
('Kỹ Sư Nhật Bản ✅', 'https://www.facebook.com/groups/729220015289631/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 102000, true),
('Tuyển dụng kỹ sư QS-Kinh tế xây dựng', 'https://www.facebook.com/groups/1890524574788351/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4500, true),
('Việc làm kỹ sư IT/BrSE Nhật Bản', 'https://www.facebook.com/groups/401261073892566/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 17000, true),
('Diễn đàn Kỹ Sư Cầu Nối (BrSE) - Giao lưu - Trao đổi', 'https://www.facebook.com/groups/268464787112051/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2500, true),
('Hội Kỹ Sư Điện Việt Nam', 'https://www.facebook.com/groups/613646268729396/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 50000, true),
('Chuyển việc Kỹ sư', 'https://www.facebook.com/groups/455311153683006/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 26000, true);
INSERT INTO sandbox.social_group_urls (name, url, group_type, member_count, is_active) VALUES
('Kỹ Sư Nhật Bản - Việc Làm', 'https://www.facebook.com/groups/2023790564767783/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 54000, true),
('Kỹ sư cầu nối (BrSE) HCM -HN -Nhật Bản', 'https://www.facebook.com/groups/309707408780063/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 942, true),
('Cộng đồng kỹ sư CAD-CAM-CAE tại Nhật', 'https://www.facebook.com/groups/kysunhatchuyenviecmienphi/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 32000, true),
('Tuyển dụng - Kỹ Sư- Kỹ thuật- Giám đốc điều hành', 'https://www.facebook.com/groups/2496241820607060/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 5800, true),
('Nhóm Kỹ sư cầu nối - Brse Việt Nhật', 'https://www.facebook.com/groups/905408546544190/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3700, true),
('Cộng Đồng Kỹ Sư MEPF Việt Nam', 'https://www.facebook.com/groups/1251246873045686/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3000, true),
('THÔNG TIN VIỆC LÀM CHO KỸ SƯ-CỬ NHÂN-SINH VIÊN - CƠ KHÍ', 'https://www.facebook.com/groups/vlck25/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6300, true),
('Hội Kỹ Sư Xây Dựng', 'https://www.facebook.com/groups/1987624372089344/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 386, true),
('Kỹ Sư Cầu Nối - BrSE Tiếng Nhật', 'https://www.facebook.com/groups/2577015569127429/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 1000, true),
('KỸ SƯ XÂY DỰNG NHẬT BẢN', 'https://www.facebook.com/groups/kysuxaydungonhat/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 47000, true),
('Cộng đồng kỹ sư bán hàng (Sale Engineer)', 'https://www.facebook.com/groups/302965937335953/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 9000, true),
('設計職専用サイト_CỘNG ĐỒNG KỸ SƯ THIẾT KẾ VIỆT-NHẬT', 'https://www.facebook.com/groups/329197685357077/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3700, true),
('🏡 TUYỂN DỤNG VIỆC LÀM KIẾN TRÚC SƯ - KỸ SƯ XÂY DỰNG - THIẾT KẾ NỘI THẤT', 'https://www.facebook.com/groups/tuyendungvieclamkientrucnoithat02/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 110000, true),
('Kỹ sư xây dựng Việt Nam', 'https://www.facebook.com/groups/201018707897745/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 7300, true),
('Tuyển Dụng Kỹ Sư Xây Dựng - Kiến Trúc Sư - Nội Thất', 'https://www.facebook.com/groups/2188380784744724/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3500, true),
('Trường ĐH Công nghệ kỹ thuật TPHCM (Sư phạm kỹ thuật TPHCM)', 'https://www.facebook.com/groups/huynhvanson/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 43000, true),
('HỘI KỸ SƯ Ô TÔ VIỆT NAM', 'https://www.facebook.com/groups/httpswww.facebook.comdemigodkylin1905/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 87000, true),
('Việc Làm Cơ Điện/ME/HVAC/PCCC - Vieclamkythuat.com', 'https://www.facebook.com/groups/1911637015973925/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 11000, true),
('Kỹ sư chuyển việc tại Nhật Bản (日本で転職する仕事) ✅', 'https://www.facebook.com/groups/756457659679335/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 167000, true),
('Kỹ sư IT, BA, Tester, PM tiếng Hàn', 'https://www.facebook.com/groups/ithanquoc/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 4900, true),
('Kỹ Sư Cầu Nối', 'https://www.facebook.com/groups/1971961879726011/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 2600, true),
('Cộng Đồng Kỹ Sư Nhật Bản', 'https://www.facebook.com/groups/359031044523161/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 53000, true),
('Kỹ Sư Cơ Khí & Việc Làm', 'https://www.facebook.com/groups/482136141817760/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 49000, true),
('KỸ SƯ NHẬT BẢN ( Cộng Đồng Kỹ Sư Đi Mới - Chuyển Việc )', 'https://www.facebook.com/groups/994259058348355/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 119000, true),
('VIỆC LÀM CƠ KHÍ CNC - KỸ SƯ SẢN XUẤT', 'https://www.facebook.com/groups/2227760201360008/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 42000, true),
('Kỹ Sư Cơ khí Tìm Việc Làm', 'https://www.facebook.com/groups/131072731022774/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6200, true),
('Việc cho người làm cơ khí ( Thợ hàn, kỹ sư, quản đốc, kỹ thuật..)', 'https://www.facebook.com/groups/viecchonguoilamcokhi/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 6800, true),
('Kỹ Sư Cơ Điện M&E', 'https://www.facebook.com/groups/421177733980982/', ARRAY['Industrial','Mechatronics','Industrial Automation','Mechanical']::text[], 3200, true);
-- PHAN 3: VERIFY (bat buoc chay va doi chieu ket qua truoc khi bao PASS)
-- Ca 2 dong deu phai tra ve dung 1028.
select 'public.social_group_urls' as t, count(*) from public.social_group_urls
union all
select 'sandbox.social_group_urls', count(*) from sandbox.social_group_urls;

-- Khong dong nao duoc phep NULL member_count hoac rong group_type.
-- Ca 2 dong deu phai tra ve 0.
select count(*) from public.social_group_urls
  where member_count is null or group_type is null or array_length(group_type,1) is null;
select count(*) from sandbox.social_group_urls
  where member_count is null or group_type is null or array_length(group_type,1) is null;
